export const generateReportHtml = (result, retrievedContext, idea, riskScore) => {
  const riskColor = riskScore > 70 ? '#ef4444' : riskScore > 40 ? '#f59e0b' : '#10b981';
  const riskLabel = riskScore > 70 ? 'HIGH RISK' : riskScore > 40 ? 'MEDIUM RISK' : 'LOW RISK';
  const date = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
  const time = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

  const stepsHtml = (Array.isArray(result.steps) ? result.steps : String(result.steps || '').split('\n')).filter(s => String(s).trim()).map((s, i) =>
    `<tr><td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;color:#6366f1;font-weight:700;width:40px;text-align:center;">${i + 1}</td><td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;color:#374151;">${String(s).replace(/^[\d.•\-)\s]+/, '').trim()}</td></tr>`
  ).join('');

  const risksHtml = (Array.isArray(result.risks) ? result.risks : String(result.risks || '').split('\n')).filter(r => String(r).trim()).map(r =>
    `<div style="padding:10px 14px;background:#fef2f2;border-left:3px solid #ef4444;border-radius:6px;margin-bottom:8px;color:#991b1b;font-size:13px;">${String(r).replace(/^[\d.•\-)\s]+/, '').trim()}</div>`
  ).join('');

  const licensesHtml = (Array.isArray(result.licenses) ? result.licenses : String(result.licenses || '').split(',')).map(l =>
    `<span style="display:inline-block;padding:6px 14px;background:#eef2ff;color:#4338ca;border-radius:20px;font-size:12px;font-weight:600;margin:4px;">${String(l).trim()}</span>`
  ).join('');

  const sourcesHtml = retrievedContext.map((ctx, i) =>
    `<tr><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-size:12px;color:#6b7280;">${i + 1}</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-size:12px;">${ctx.ref ? `<a href="${ctx.ref}" style="color:#4f46e5;">${ctx.source}</a>` : ctx.source}</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-size:12px;color:#6b7280;">Page ${ctx.page_number || '?'}</td><td style="padding:8px 12px;border-bottom:1px solid #f3f4f6;font-size:12px;color:#6b7280;">${Math.round((ctx.score || 0) * 100)}%</td></tr>`
  ).join('');

  const rawHtml = (result.raw || '').replace(/\n/g, '<br/>').replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" style="color:#4f46e5;">$1</a>');

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Legal Compliance Report — ${result.businessType}</title>
  <style>body{font-family:'Segoe UI',Arial,sans-serif;max-width:800px;margin:0 auto;padding:40px;color:#111827;line-height:1.6;}
  h1{font-size:24px;color:#1e1b4b;margin-bottom:4px;}h2{font-size:16px;color:#4f46e5;text-transform:uppercase;letter-spacing:0.05em;margin-top:36px;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #e5e7eb;}
  .header{border-bottom:3px solid #4f46e5;padding-bottom:20px;margin-bottom:30px;}
  .meta{font-size:13px;color:#6b7280;margin-top:4px;}
  .risk-badge{display:inline-block;padding:6px 16px;border-radius:20px;font-weight:700;font-size:13px;color:white;}
  table{width:100%;border-collapse:collapse;}th{text-align:left;padding:8px 12px;background:#f8fafc;border-bottom:2px solid #e5e7eb;font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:0.05em;}
  .footer{margin-top:40px;padding-top:20px;border-top:2px solid #e5e7eb;text-align:center;font-size:12px;color:#9ca3af;}
  @media print{body{padding:20px;}}</style></head><body>
  <div class="header">
    <div style="display:flex;justify-content:space-between;align-items:flex-start;">
      <div><h1>⚖️ LexAgent</h1><div class="meta">AI Compliance Report · ${date} at ${time}</div></div>
      <div style="text-align:right;"><span class="risk-badge" style="background:${riskColor};">${riskLabel}: ${riskScore}/100</span></div>
    </div>
  </div>
  <h2>📌 Business Overview</h2>
  <table><tr><td style="padding:10px;font-weight:600;color:#6b7280;width:140px;">Business Type</td><td style="padding:10px;font-weight:600;">${result.businessType}</td></tr>
  <tr><td style="padding:10px;font-weight:600;color:#6b7280;">Estimated Cost</td><td style="padding:10px;">${result.cost}</td></tr>
  <tr><td style="padding:10px;font-weight:600;color:#6b7280;">Business Idea</td><td style="padding:10px;font-size:13px;color:#374151;">${idea}</td></tr></table>
  <h2>📄 Required Licenses & Compliance</h2><div style="margin:12px 0;">${licensesHtml}</div>
  <h2>⚙️ Action Plan</h2><table>${stepsHtml}</table>
  <h2>⚠️ Legal Risks</h2>${risksHtml}
  <h2>📝 Detailed AI Analysis</h2><div style="background:#f8fafc;padding:20px;border-radius:8px;font-size:13px;color:#374151;line-height:1.8;">${rawHtml}</div>
  <h2>📚 Referenced Documents (${retrievedContext.length})</h2>
  <table><thead><tr><th>#</th><th>Document</th><th>Page</th><th>Relevance</th></tr></thead><tbody>${sourcesHtml}</tbody></table>
  <div class="footer"><p>Generated by <strong>LexAgent AI</strong> · Powered by Gemini LLM + Qdrant Vector Search</p><p>This report is AI-generated and should be reviewed by a qualified legal professional.</p></div>
  </body></html>`;

  return html;
};

export const downloadReport = (result, retrievedContext, idea, riskScore) => {
  const html = generateReportHtml(result, retrievedContext, idea, riskScore);
  const blob = new Blob([html], { type: 'text/html' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `LexAgent-Report-${result.businessType.replace(/\s+/g, '-')}-${Date.now()}.html`;
  link.click();
};
